config/routes.rb
Shindo::Application.routes.draw do
  resources :cities, :only => [:index, :show] do
    get :search, :on => :collection
    get :plot, :on => :member
  end
  resources :regions, :only => [:index, :show] { get 'plot', :on => :member }
  resources :quakes, :only => [:index, :show] { get 'plot', :on => :collection }
  root :to => "cities#index"

end

app/models/city.rb
# -*- coding: utf-8 -*-

class City < ActiveRecord::Base

  include Location

  def name 
    if name_en
      "#{name_en} (#{name_ja})"
    else
      "#{name_ja}"
    end
  end

end

app/controllers/cities_controller.rb
# -*- coding: utf-8 -*-


class CitiesController < ApplicationController

  caches_page :show

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => City.all }
      format.xml  { render :xml => City.all }
    end
  end

  def show
    @city = City.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @city.intensities.to_json(:only => [:value], :methods => [:time]) }
      format.xml  { render :xml => @city.intensities }
    end
  end

  def plot
    min = Time.at(((params[:min] || 0).to_i - Time.zone.utc_offset)/1000)
    max = Time.at(((params[:max] || 0).to_i - Time.zone.utc_offset)/1000)
    @data = City.find(params[:id]).intensities.includes(:quake).where("quakes.quake_time > ? and quakes.quake_time < ?", min, max).order("quakes.quake_time").map { |i| [
        (i.quake.quake_time.to_i+Time.zone.utc_offset)*1000,
        i.value_i,
        url_for(i.quake),
        "#{l i.quake.quake_time}<br>#{i.quake.region.name}<br>M#{i.quake.magnitude} - #{i.quake.depth}"
    ] }
    respond_to do |format|
      format.json { render :json => @data }
    end
  end

  def search
    term = params[:term]
    @data = City.where("lower(name_en) like ? or lower(name_ja) like ?", "%#{term.downcase}%", "%#{term.downcase}%").all.map do |c|
      { :id => c.id, :label => c.name  }
    end
    respond_to do |format|
      format.json { render :json => @data }
    end
  end


end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<h1>Earthquake intensity by location</h1>
<div class="ui-widget">
  <label for="search">Location: </label>
  <input id="search" data-src="<%= search_cities_url(:format => :json) %>"/>
</div>
<%= link_to "All quakes", quakes_path %>

app/views/cities/show.html.erb
<h1>Earthquake intensities in <%= @city.name %></h1>

<div class="ui-widget">
  <label for="search">Location: </label>
  <input id="search" data-src="<%= search_cities_url(:format => :json) %>"/>
</div>
<%= link_to "All quakes", quakes_path %>
<br>

<div data-src="<%= plot_city_url(:format => :json) %>" class="intensity timeplot"><%= image_tag "loader.gif" %></div>

<table>
<% @city.intensities.includes(:quake).order('quakes.quake_time desc').reverse.each do |intensity| %>
  <tr>
    <td><%= l intensity.time %></td>
    <td><%= intensity.value %></td>
  </tr>
<% end %>
</table>


<%= link_to 'Back', cities_path %>