config/routes.rb
Shindo::Application.routes.draw do
  resources :cities, :only => [:index, :show] do
    get :search, :on => :collection
    get :plot, :on => :member
  end
  resources :regions, :only => [:index, :show] { get 'plot', :on => :member }
  resources :quakes, :only => [:index, :show] { get 'plot', :on => :collection }
  root :to => "cities#index"

end

app/models/region.rb
# -*- coding: utf-8 -*-

class Region < ActiveRecord::Base

  has_many :quakes

  include Location

  def name
    if name_en
      "#{name_en} (#{name_ja})"
    else
      "#{name_ja}"
    end
  end

end

app/controllers/regions_controller.rb
# -*- coding: utf-8 -*-

class RegionsController < ApplicationController
  caches_page :show

  def index
    @regions = Region.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @regions }
    end
  end

  def show
    @region = Region.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @region }
    end
  end

end

app/views/regions/index.html.erb
<h1>Listing regions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @regions.each do |region| %>
  <tr>
    <td><%= region.name_ja %></td>
    <td><%= link_to 'Show', region %></td>
  </tr>
<% end %>
</table>

app/views/regions/show.html.erb
<table>
<% @region.intensities.each do |intensity| %>
  <tr>
    <td><%= intensity.time %></td>
    <td><%= intensity.value %></td>
  </tr>
<% end %>
</table>


<%= link_to 'Back', regions_path %>